# when we have two application.yml, the application-something.yml will inherit all the properties from the application.yml
# then u can override what need to be override

# connection to database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network # will be created in the container automatically
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true  # it works with show-sql
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail: # SMTP server host
    host: localhost
    port: 1025
    username: othmane
    password: othmane
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000 # 3s
        writetimeout: 5000
